"""Errand list skill for Personal Ops.

Generates organized errand lists.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("errand_list")
class ErrandListSkill:
    """Generate organized errand list.

    Produces an errand list with:
    - Errands grouped by location/category
    - Priority levels
    - Notes/details

    Contract-compliant with deterministic mode.
    """

    name = "errand_list"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for errand lists."""
        template_str = """# Errand List: {{ date }}

{% for location, items in errands_by_location.items() %}
## {{ location }}

{% for item in items %}
- [{% if item.priority == "high" %}!{% else %} {% endif %}] {{ item.task }}{% if item.notes %} - *{{ item.notes }}*{% endif %}
{% endfor %}

{% endfor %}

---
*Generated by AG Network Personal Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with errands list
            context: Runtime context

        Returns:
            SkillResult with errand list artifact
        """
        # Extract inputs
        date = inputs.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        errands = inputs.get("errands", [])

        # Group errands by location
        errands_by_location = {}
        for errand in errands:
            location = errand.get("location", "General")
            if location not in errands_by_location:
                errands_by_location[location] = []
            errands_by_location[location].append(errand)

        # Generate markdown
        markdown = self.template.render(
            date=date,
            errands_by_location=errands_by_location,
        )

        # Build JSON data
        json_data = {
            "date": date,
            "errands": errands,
            "errands_by_location": errands_by_location,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"errand_list_{date}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"errand_list_{date}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claims for errands
        claims = [
            Claim(
                text=errand.get("task", ""),
                kind=ClaimKind.ASSUMPTION,
                source_refs=[],
                evidence=[],
            )
            for errand in errands
        ]

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def generate(
        self,
        errands: list[dict],
        date: str = None,
    ) -> tuple[str, dict]:
        """Generate errand list (legacy interface).

        Args:
            errands: List of errand dicts with task, location, priority, notes
            date: Date for the list

        Returns:
            Tuple of (markdown, json_data)
        """
        if date is None:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        inputs = {
            "date": date,
            "errands": errands,
        }

        ctx = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, ctx)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
