"""Travel outline skill for Personal Ops.

Generates travel itinerary outlines.
"""

import json
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("travel_outline")
class TravelOutlineSkill:
    """Generate travel itinerary outline.

    Produces a travel outline with:
    - Trip details (destination, dates)
    - Accommodation info
    - Day-by-day activities
    - Packing checklist
    - Important notes

    Contract-compliant with deterministic mode.
    """

    name = "travel_outline"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for travel outlines."""
        template_str = """# Travel Outline: {{ destination }}

**Dates**: {{ start_date }} - {{ end_date }}

{% if accommodation %}
## Accommodation

{{ accommodation }}
{% endif %}

## Itinerary

{% for day in itinerary %}
### Day {{ loop.index }}: {{ day.date }}

{% for activity in day.activities %}
- {{ activity }}
{% endfor %}

{% endfor %}

{% if packing_list %}
## Packing Checklist

{% for item in packing_list %}
- [ ] {{ item }}
{% endfor %}
{% endif %}

{% if notes %}
## Important Notes

{% for note in notes %}
- {{ note }}
{% endfor %}
{% endif %}

---
*Generated by AG Network Personal Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with destination, dates, itinerary
            context: Runtime context

        Returns:
            SkillResult with travel outline artifact
        """
        # Extract inputs
        destination = inputs.get("destination", "Trip")
        start_date = inputs.get("start_date", "")
        end_date = inputs.get("end_date", "")
        accommodation = inputs.get("accommodation", "")
        itinerary = inputs.get("itinerary", [])
        packing_list = inputs.get("packing_list", [])
        notes = inputs.get("notes", [])

        # Generate markdown
        markdown = self.template.render(
            destination=destination,
            start_date=start_date,
            end_date=end_date,
            accommodation=accommodation,
            itinerary=itinerary,
            packing_list=packing_list,
            notes=notes,
        )

        # Build JSON data
        json_data = {
            "destination": destination,
            "start_date": start_date,
            "end_date": end_date,
            "accommodation": accommodation,
            "itinerary": itinerary,
            "packing_list": packing_list,
            "notes": notes,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"travel_outline_{start_date}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"travel_outline_{start_date}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claims for activities
        claims = []
        for day in itinerary:
            for activity in day.get("activities", []):
                claims.append(
                    Claim(
                        text=activity,
                        kind=ClaimKind.ASSUMPTION,
                        source_refs=[],
                        evidence=[],
                    )
                )

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def generate(
        self,
        destination: str,
        start_date: str,
        end_date: str,
        itinerary: list[dict],
        accommodation: str = "",
        packing_list: list[str] = None,
        notes: list[str] = None,
    ) -> tuple[str, dict]:
        """Generate travel outline (legacy interface).

        Args:
            destination: Destination name
            start_date: Trip start date
            end_date: Trip end date
            itinerary: List of day dicts with date and activities
            accommodation: Accommodation details
            packing_list: List of items to pack
            notes: Important notes

        Returns:
            Tuple of (markdown, json_data)
        """
        inputs = {
            "destination": destination,
            "start_date": start_date,
            "end_date": end_date,
            "accommodation": accommodation,
            "itinerary": itinerary,
            "packing_list": packing_list or [],
            "notes": notes or [],
        }

        ctx = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, ctx)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
