"""Weekly plan skill for Personal Ops.

Generates structured weekly plans.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("weekly_plan")
class WeeklyPlanSkill:
    """Generate weekly plan from goals and tasks.

    Produces a structured weekly plan with:
    - Week period
    - Primary goals
    - Tasks by day
    - Notes/reminders

    Contract-compliant with deterministic mode.
    """

    name = "weekly_plan"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for weekly plans."""
        template_str = """# Weekly Plan: {{ week_of }}

## Primary Goals

{% for goal in goals %}
- {{ goal }}
{% endfor %}

## Daily Tasks

{% for day, tasks in daily_tasks.items() %}
### {{ day }}

{% for task in tasks %}
- {{ task }}
{% endfor %}

{% endfor %}

{% if notes %}
## Notes & Reminders

{% for note in notes %}
- {{ note }}
{% endfor %}
{% endif %}

---
*Generated by AG Network Personal Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with week_of, goals, daily_tasks
            context: Runtime context

        Returns:
            SkillResult with weekly plan artifact
        """
        # Extract inputs
        week_of = inputs.get("week_of", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        goals = inputs.get("goals", [])
        daily_tasks = inputs.get("daily_tasks", {})
        notes = inputs.get("notes", [])

        # Generate markdown
        markdown = self.template.render(
            week_of=week_of,
            goals=goals,
            daily_tasks=daily_tasks,
            notes=notes,
        )

        # Build JSON data
        json_data = {
            "week_of": week_of,
            "goals": goals,
            "daily_tasks": daily_tasks,
            "notes": notes,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"weekly_plan_{week_of}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"weekly_plan_{week_of}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claims for goals
        claims = [
            Claim(
                text=goal,
                kind=ClaimKind.ASSUMPTION,
                source_refs=[],
                evidence=[],
            )
            for goal in goals
        ]

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def generate(
        self,
        goals: list[str],
        daily_tasks: dict[str, list[str]],
        notes: list[str] = None,
        week_of: str = None,
    ) -> tuple[str, dict]:
        """Generate weekly plan (legacy interface).

        Args:
            goals: List of primary goals
            daily_tasks: Dict mapping day names to task lists
            notes: Optional notes/reminders
            week_of: Week start date

        Returns:
            Tuple of (markdown, json_data)
        """
        if week_of is None:
            week_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        inputs = {
            "week_of": week_of,
            "goals": goals,
            "daily_tasks": daily_tasks,
            "notes": notes or [],
        }

        ctx = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, ctx)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
