"""Decision log skill for Work Ops.

Generates ADR-style decision records.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("decision_log")
class DecisionLogSkill:
    """Generate ADR-style decision log.

    Produces a structured decision record with:
    - Decision title and date
    - Context/background
    - Options considered
    - Decision made
    - Consequences/implications

    Follows Architecture Decision Record (ADR) format.
    Contract-compliant with deterministic mode.
    """

    name = "decision_log"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for decision logs."""
        template_str = """# Decision Record: {{ title }}

**Date**: {{ date }}
**Status**: {{ status }}
**Decision Makers**: {{ decision_makers }}

## Context

{{ context }}

## Options Considered

{% for option in options %}
### Option {{ loop.index }}: {{ option.name }}

{{ option.description }}

**Pros:**
{% for pro in option.pros %}
- {{ pro }}
{% endfor %}

**Cons:**
{% for con in option.cons %}
- {{ con }}
{% endfor %}

{% endfor %}

## Decision

{{ decision }}

## Consequences

{% for consequence in consequences %}
- {{ consequence }}
{% endfor %}

---
*Generated by AG Network Work Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with title, context, options, decision
            context: Runtime context

        Returns:
            SkillResult with decision log artifact
        """
        # Extract inputs
        title = inputs.get("title", "Decision")
        date = inputs.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        status = inputs.get("status", "Accepted")
        decision_makers = inputs.get("decision_makers", "Team")
        decision_context = inputs.get("context", "")
        options = inputs.get("options", [])
        decision = inputs.get("decision", "")
        consequences = inputs.get("consequences", [])

        # Generate markdown
        markdown = self.template.render(
            title=title,
            date=date,
            status=status,
            decision_makers=decision_makers,
            context=decision_context,
            options=options,
            decision=decision,
            consequences=consequences,
        )

        # Build JSON data
        json_data = {
            "title": title,
            "date": date,
            "status": status,
            "decision_makers": decision_makers,
            "context": decision_context,
            "options": options,
            "decision": decision,
            "consequences": consequences,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"decision_log_{date}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"decision_log_{date}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claim for the decision
        claims = [
            Claim(
                text=decision,
                kind=ClaimKind.FACT,
                source_refs=[],
                evidence=[],
            )
        ]

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def generate(
        self,
        title: str,
        context: str,
        options: list[dict],
        decision: str,
        consequences: list[str] = None,
        decision_makers: str = "Team",
        status: str = "Accepted",
    ) -> tuple[str, dict]:
        """Generate decision log (legacy interface).

        Args:
            title: Decision title
            context: Background context
            options: List of option dicts with name, description, pros, cons
            decision: The decision made
            consequences: List of consequences
            decision_makers: Who made the decision
            status: Status (Accepted, Proposed, etc.)

        Returns:
            Tuple of (markdown, json_data)
        """
        inputs = {
            "title": title,
            "context": context,
            "options": options,
            "decision": decision,
            "consequences": consequences or [],
            "decision_makers": decision_makers,
            "status": status,
        }

        ctx = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, ctx)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
