"""Meeting summary skill for Work Ops.

Generates structured summaries from meeting notes.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("meeting_summary")
class MeetingSummarySkill:
    """Generate meeting summary from notes.

    Produces a structured summary with:
    - Meeting metadata (date, attendees, topic)
    - Key discussion points
    - Decisions made
    - Action items with owners

    Contract-compliant with deterministic/manual mode support.
    """

    name = "meeting_summary"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for meeting summaries."""
        template_str = """# Meeting Summary: {{ topic }}

**Date**: {{ date }}
**Attendees**: {{ attendees }}

## Key Discussion Points

{% for point in discussion_points %}
- {{ point }}
{% endfor %}

## Decisions Made

{% for decision in decisions %}
- {{ decision }}
{% endfor %}

## Action Items

{% for item in action_items %}
- **{{ item.owner }}**: {{ item.task }}{% if item.due_date %} (Due: {{ item.due_date }}){% endif %}
{% endfor %}

---
*Generated by AG Network Work Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with topic, notes, attendees
            context: Runtime context

        Returns:
            SkillResult with summary artifact
        """
        # Extract inputs
        topic = inputs.get("topic", "Meeting")
        date = inputs.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        attendees = inputs.get("attendees", "N/A")
        notes = inputs.get("notes", "")

        # Parse notes into structured sections (deterministic)
        discussion_points, decisions, action_items = self._parse_notes(notes)

        # Generate markdown
        markdown = self.template.render(
            topic=topic,
            date=date,
            attendees=attendees,
            discussion_points=discussion_points,
            decisions=decisions,
            action_items=action_items,
        )

        # Build JSON data
        json_data = {
            "topic": topic,
            "date": date,
            "attendees": attendees,
            "discussion_points": discussion_points,
            "decisions": decisions,
            "action_items": action_items,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"meeting_summary_{date}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"meeting_summary_{date}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claims for decisions
        claims = [
            Claim(
                text=decision,
                kind=ClaimKind.FACT,
                source_refs=[],
                evidence=[],
            )
            for decision in decisions
        ]

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def _parse_notes(self, notes: str) -> tuple[list[str], list[str], list[dict]]:
        """Parse notes into structured sections.

        Simple deterministic parsing:
        - Lines starting with "- " are discussion points
        - Lines starting with "DECISION: " are decisions
        - Lines starting with "ACTION: " are action items

        Args:
            notes: Raw meeting notes

        Returns:
            Tuple of (discussion_points, decisions, action_items)
        """
        discussion_points = []
        decisions = []
        action_items = []

        for line in notes.split("\n"):
            line = line.strip()
            if not line:
                continue

            if line.startswith("DECISION:"):
                decisions.append(line.replace("DECISION:", "").strip())
            elif line.startswith("ACTION:"):
                # Parse ACTION: Owner - Task (Due: Date)
                action_text = line.replace("ACTION:", "").strip()
                parts = action_text.split("-", 1)
                if len(parts) == 2:
                    owner = parts[0].strip()
                    task_and_due = parts[1].strip()
                    due_date = None
                    task = task_and_due

                    if "(Due:" in task_and_due:
                        task, due_part = task_and_due.split("(Due:", 1)
                        due_date = due_part.replace(")", "").strip()
                        task = task.strip()

                    action_items.append({"owner": owner, "task": task, "due_date": due_date})
                else:
                    action_items.append({"owner": "Unassigned", "task": action_text, "due_date": None})
            elif line.startswith("-"):
                discussion_points.append(line[1:].strip())
            else:
                # Default to discussion point
                discussion_points.append(line)

        return discussion_points, decisions, action_items

    def generate(
        self,
        topic: str,
        notes: str,
        date: str = None,
        attendees: str = "N/A",
    ) -> tuple[str, dict]:
        """Generate meeting summary (legacy interface).

        Args:
            topic: Meeting topic
            notes: Raw meeting notes
            date: Meeting date
            attendees: Comma-separated attendees

        Returns:
            Tuple of (markdown, json_data)
        """
        if date is None:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        inputs = {
            "topic": topic,
            "notes": notes,
            "date": date,
            "attendees": attendees,
        }

        context = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, context)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
