"""Status update skill for Work Ops.

Generates weekly status updates from bullet points.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict

from jinja2 import Template

from agnetwork.kernel.contracts import (
    ArtifactKind,
    ArtifactRef,
    Claim,
    ClaimKind,
    SkillContext,
    SkillMetrics,
    SkillResult,
)
from agnetwork.kernel.executor import register_skill


@register_skill("status_update")
class StatusUpdateSkill:
    """Generate status update from bullet points.

    Produces a structured status update with:
    - Summary period
    - Accomplishments
    - In progress work
    - Blockers/challenges
    - Next week priorities

    Contract-compliant with deterministic mode.
    """

    name = "status_update"
    version = "1.0"

    def __init__(self):
        """Initialize the skill."""
        self.template = self._get_template()

    def _get_template(self) -> Template:
        """Get the Jinja2 template for status updates."""
        template_str = """# Status Update: {{ period }}

**Author**: {{ author }}
**Date**: {{ date }}

## Accomplishments

{% for item in accomplishments %}
- {{ item }}
{% endfor %}

## In Progress

{% for item in in_progress %}
- {{ item }}
{% endfor %}

{% if blockers %}
## Blockers & Challenges

{% for item in blockers %}
- {{ item }}
{% endfor %}
{% endif %}

## Next Week Priorities

{% for item in next_week %}
- {{ item }}
{% endfor %}

---
*Generated by AG Network Work Ops*
"""
        return Template(template_str)

    def run(self, inputs: Dict[str, Any], context: SkillContext) -> SkillResult:
        """Execute the skill with standard contract.

        Args:
            inputs: Dict with period, accomplishments, in_progress, etc.
            context: Runtime context

        Returns:
            SkillResult with status update artifact
        """
        # Extract inputs
        period = inputs.get("period", "This Week")
        author = inputs.get("author", "Team Member")
        date = inputs.get("date", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        accomplishments = inputs.get("accomplishments", [])
        in_progress = inputs.get("in_progress", [])
        blockers = inputs.get("blockers", [])
        next_week = inputs.get("next_week", [])

        # Generate markdown
        markdown = self.template.render(
            period=period,
            author=author,
            date=date,
            accomplishments=accomplishments,
            in_progress=in_progress,
            blockers=blockers,
            next_week=next_week,
        )

        # Build JSON data
        json_data = {
            "period": period,
            "author": author,
            "date": date,
            "accomplishments": accomplishments,
            "in_progress": in_progress,
            "blockers": blockers,
            "next_week": next_week,
        }

        # Create artifact references (MD and JSON)
        artifacts = [
            ArtifactRef(
                name=f"status_update_{date}",
                kind=ArtifactKind.MARKDOWN,
                content=markdown,
            ),
            ArtifactRef(
                name=f"status_update_{date}",
                kind=ArtifactKind.JSON,
                content=json.dumps(json_data, indent=2),
            ),
        ]

        # Create claims for accomplishments
        claims = [
            Claim(
                text=item,
                kind=ClaimKind.FACT,
                source_refs=[],
                evidence=[],
            )
            for item in accomplishments
        ]

        return SkillResult(
            success=True,
            output=json_data,
            artifacts=artifacts,
            claims=claims,
            metrics=SkillMetrics(),
            next_actions=[],
        )

    def generate(
        self,
        accomplishments: list[str],
        in_progress: list[str] = None,
        blockers: list[str] = None,
        next_week: list[str] = None,
        period: str = "This Week",
        author: str = "Team Member",
    ) -> tuple[str, dict]:
        """Generate status update (legacy interface).

        Args:
            accomplishments: List of completed items
            in_progress: List of in-progress items
            blockers: List of blockers/challenges
            next_week: List of next week priorities
            period: Time period covered
            author: Author name

        Returns:
            Tuple of (markdown, json_data)
        """
        inputs = {
            "period": period,
            "author": author,
            "accomplishments": accomplishments,
            "in_progress": in_progress or [],
            "blockers": blockers or [],
            "next_week": next_week or [],
        }

        context = SkillContext(run_id="manual", workspace="manual")
        result = self.run(inputs, context)

        # Extract markdown and JSON from artifacts
        md_content = result.artifacts[0].content
        json_content = json.loads(result.artifacts[1].content)

        return md_content, json_content
